// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Connection string for your primary database
    url: process.env.DATABASE_URL,
    // Optional: shadow database URL used by Prisma Migrate
    // shadowUrl: process.env.SHADOW_DATABASE_URL,
    // Optional: pooled/direct connection URL (e.g., PgBouncer)
    // directUrl: process.env.DIRECT_DATABASE_URL,
  },
});
